<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button lanjutkan</name>
   <tag></tag>
   <elementGuidId>fc5a9f3f-94a7-4600-a144-9ba1b2a33c38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.width180</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Lanjutkan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b72dfff9-c471-42da-b41b-0b8451fdd27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3814b1b1-7d12-4d96-bcb7-31aa3249874b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Lanjutkan</value>
      <webElementGuid>7ba383a1-a1f3-4469-a8f6-396d6f57cfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary width180</value>
      <webElementGuid>be0aef2d-067b-4454-9fc9-0d1d44e4ccd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='//www.pegipegi.com/tiket-pesawat/sys/transaction/detailkontak';</value>
      <webElementGuid>c47d8725-deab-45a4-9f83-86f7b7183fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;paymentPage&quot;]/div[@class=&quot;outer-wrapper data-pemesanan&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;formAction&quot;]/input[@class=&quot;btn btn-primary width180&quot;]</value>
      <webElementGuid>f54b3101-a0d5-4b14-bf23-a18d873f9ead</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Lanjutkan']</value>
      <webElementGuid>ed2129cb-6312-4e9a-9160-2f266d8665ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>35663377-3ba9-4743-a32c-27ab981df0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>895529fe-f3ac-484a-afe6-36a085b6b55d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
