<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button tiket pergi</name>
   <tag></tag>
   <elementGuidId>b951c998-3553-433e-9c89-8d2818306416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Pesan Tiket Pergi'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f46f9053-c710-4fa1-bfbf-4100127572b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3ec3ef52-36ee-46e3-933a-4d72bc77e6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pesan Tiket Pergi</value>
      <webElementGuid>75acef17-a51d-41e3-874d-976ddd37f065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>766660bb-c46e-44ee-b03c-737c6e65a515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pesanTiket('Pergi', this)</value>
      <webElementGuid>00fd6785-9133-404d-abca-3dbc9fc1a0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CGK_YIA_20230315_8B5536_1655_1805_SQW&quot;)/div[@class=&quot;buttonBuy&quot;]/input[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>0dde8295-414d-4e95-b960-94a92f7bb0ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Pesan Tiket Pergi']</value>
      <webElementGuid>36aca291-439a-4517-bf42-1d08e5fec1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CGK_YIA_20230315_8B5536_1655_1805_SQW']/div[7]/input</value>
      <webElementGuid>6b1f6841-1e78-4e19-947c-3665817f8780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>c5bf2ef7-6adf-4a9d-887d-46530d2aa7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>b3275cee-b5ef-4b3b-b1d6-1b1360f6683c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
