<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_cari_tiket</name>
   <tag></tag>
   <elementGuidId>a55f46f2-c879-456d-bf06-4049ff9f2dcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cari_tiket</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cari_tiket']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87cc68f1-8b9a-4444-9d49-5889525038d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>67bf1d28-3b8b-47c9-9806-105b5dc1fbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>d2a1aba1-995c-4d30-9ea9-ce11c376ca20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cari Tiket</value>
      <webElementGuid>66dbdcea-554c-49a0-bb2a-27529b179f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cari_tiket</value>
      <webElementGuid>bf7c928a-6177-436d-9eda-32eba297a81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cari Tiket</value>
      <webElementGuid>629011a6-38b6-4506-9bc5-7e4db9c580c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cari_tiket&quot;)</value>
      <webElementGuid>88d12b92-3e6a-4e94-838a-5c717b7af556</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cari_tiket']</value>
      <webElementGuid>0395cd07-3c38-4242-b9ab-2b0bada5f9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cari Tiket')]</value>
      <webElementGuid>48d9efb3-4034-453d-a694-ed569eb8393e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiket Pesawat'])[2]/preceding::a[1]</value>
      <webElementGuid>9742366b-c806-4f29-8bed-96c3427dd5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari Tiket']/parent::*</value>
      <webElementGuid>bc726ce4-90bc-4711-b2f5-0302dd90342f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]</value>
      <webElementGuid>96bd3002-f450-49f8-8b67-22904344ad1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Cari Tiket' and @id = 'cari_tiket' and (text() = ' Cari Tiket' or . = ' Cari Tiket')]</value>
      <webElementGuid>363ccbf7-763c-4001-bf30-b0b06200119d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
