<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Navigation pesawat</name>
   <tag></tag>
   <elementGuidId>c1ef4f37-1c9c-43a5-a629-b0aca946b6e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Pesawat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df3cfc47-463b-4ad2-884b-47ca643e145d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//www.pegipegi.com/tiket-pesawat/</value>
      <webElementGuid>f5c66e4b-c632-453b-a2f7-830c9370d46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pesawat</value>
      <webElementGuid>c9b2b94b-f641-4274-9219-7535e26edb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index-page&quot;)/body[1]/div[@class=&quot;outer-wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;menuHeader-wrapper&quot;]/div[@class=&quot;menuHeader&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[2]/a[1]</value>
      <webElementGuid>725d032d-cb97-441c-be55-c92489388f7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='index-page']/body/div/div[2]/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>777d60ea-89b4-4dc6-8d78-37b032a11c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotel'])[1]/following::a[1]</value>
      <webElementGuid>64f7cccb-260d-4f3d-9a38-469db41a2d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kereta Api'])[1]/preceding::a[1]</value>
      <webElementGuid>10ba38d8-2dd0-45b0-9aa6-c93da006d9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '//www.pegipegi.com/tiket-pesawat/')]</value>
      <webElementGuid>a7602c42-b09b-426d-85c5-4d9a602647c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>08abf357-ce25-4b38-b6ee-b72bb433db4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '//www.pegipegi.com/tiket-pesawat/' and (text() = ' Pesawat' or . = ' Pesawat')]</value>
      <webElementGuid>436037c9-3d4b-4490-bb05-515010ed054d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
