<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_data</name>
   <tag></tag>
   <elementGuidId>ac362e17-b5f4-402e-a1d4-36174ad98ddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.prosesMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ModalKartuKredit']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7104b226-7502-4934-be1d-f70bc89bd94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prosesMessage</value>
      <webElementGuid>3dbed434-56df-4251-bae8-2504de2f1dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kami sedang memproses tiket pesawat Anda. Silakan menunggu beberapa menit.</value>
      <webElementGuid>afb51188-31ae-4053-8e24-9d2a23b5a79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalKartuKredit&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;StepTwo&quot;]/div[@class=&quot;contentStepTwo&quot;]/div[@class=&quot;prosesMessage&quot;]</value>
      <webElementGuid>0d7c05fb-6b2e-4599-9b8c-5a69571503f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalKartuKredit']/div/div[2]/div/div</value>
      <webElementGuid>57c82cc6-ad77-4517-8a9b-965d7725de5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang memproses pemesanan Anda dan melakukan konfirmasi Harga ke maskapai.'])[1]/following::div[3]</value>
      <webElementGuid>97dcc83b-7fe6-4f6b-ba9b-bba3c9e75672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data ini dibutuhkan'])[1]/following::div[12]</value>
      <webElementGuid>3388670a-9384-49c7-9c73-a218635a4005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perubahan Harga'])[1]/preceding::div[3]</value>
      <webElementGuid>258db4f8-c12a-4797-94ce-3e9b35cc3475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kami sedang memproses tiket pesawat Anda. Silakan menunggu beberapa menit.']/parent::*</value>
      <webElementGuid>68323205-39cd-467b-9b59-961f769b0729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>148c5a4c-625b-410a-b485-6ae6b34a68ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kami sedang memproses tiket pesawat Anda. Silakan menunggu beberapa menit.' or . = 'Kami sedang memproses tiket pesawat Anda. Silakan menunggu beberapa menit.')]</value>
      <webElementGuid>b65d3bcd-3601-4aa6-a105-2281069d2db0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
