<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input phone</name>
   <tag></tag>
   <elementGuidId>3855b83f-bd7e-491e-9051-ba5ae76d8cba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.noTelp.text-form.mini.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7a3c62d-fc4b-42a6-a276-73227370bc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9795a32-d255-4201-a60f-6d9f21e05c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noTelp text-form mini form-control</value>
      <webElementGuid>0f0e9ff6-c2d1-4bbc-a0c0-9f081062a3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cth: 081811111</value>
      <webElementGuid>f16572be-3252-4e28-a34a-93c084fefefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>dbd954af-fae5-4953-84ff-792b3a4f7bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;paymentPage&quot;]/div[@class=&quot;outer-wrapper data-kontak&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;widget&quot;]/div[@class=&quot;formLine&quot;]/div[@class=&quot;frForm&quot;]/input[@class=&quot;noTelp text-form mini form-control&quot;]</value>
      <webElementGuid>ff7457f2-ea29-45f0-bc1f-6f3894e77aab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>ad2ad43a-4420-439a-8203-68b37f173ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>19ee4e88-3c26-4cce-85a4-7f67196e244d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Cth: 081811111']</value>
      <webElementGuid>90503fd7-0560-41dd-a2d2-377f612f8037</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
